services:
  api:
    image: api:latest
    container_name: api_test_android
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    expose:
      - "5000"
    volumes:
      - product_images:/app/wwwroot/product
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_test_android
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certs/cert.pem:/etc/ssl/certs/cert.pem:ro
    - ./certs/privkey.pem:/etc/ssl/private/privkey.pem:ro
    command: ["/bin/sh", "-c", "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    depends_on:
    - api
    restart: unless-stopped
volumes:
  product_images: